#Settings required to run scripts
#Rename this file to settings.yaml before uploading to cluster
riak-host: #host ip for riak node
riak-port: #host port for riak node
stop-word-file: stopWords.txt #filename or url for stopword txt file
json-data: #location where Reddit JSON comment data is stored
orc-data: #location to save and load ORC data
word2vec-model: #location to save word2vec model
subreddit-vectors: #location to save vectors for subreddits
author-vectors: #location to save vectors for authors
numPartitions: #number of partitions for word2vec, should be the same as partitions for spark
